// Run with PLAYWRIGHT_PATH=/path/to/playwright/index.mjs node tests/browser.mjs
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import http from 'node:http';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH || 'playwright');
const directory=path.resolve(import.meta.dirname,'..');
const profile=await mkdtemp(path.join(tmpdir(),'titan-browser-test-'));
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Titan fixture '+req.url+'</title><body><h1>Titan test page</h1><a href="/destination">Destination link</a><input aria-label="Typing test"><div style="height:4000px">Long page</div></body>');});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
const base=`http://127.0.0.1:${server.address().port}`;
let context;
try {
  context=await chromium.launchPersistentContext(profile,{executablePath:process.env.CHROMIUM_PATH || '/usr/lib/chromium/chromium',headless:true,args:[`--disable-extensions-except=${directory}`,`--load-extension=${directory}`,'--no-sandbox']});
  const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  let worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  const id=new URL(worker.url()).host;
  const page=await context.newPage();
  // Open shadows only in extension-page tests to inspect controls; shipped UI stays closed.
  await page.addInitScript(()=>{const original=Element.prototype.attachShadow;Element.prototype.attachShadow=function(options){return original.call(this,{...options,mode:'open'});};});
  await page.goto(`chrome-extension://${id}/settings.html`);
  await page.getByRole('textbox',{name:'Custom slash shortcuts'}).fill(`fixture: ${base}/shortcut Fixture shortcut\ng!: ${base}/bang Google\nfixture_long: ${base}/long`);
  await page.getByRole('button',{name:'+ Add folder',exact:true}).click();
  await page.getByRole('textbox',{name:'Folder name',exact:true}).fill('Work');
  await page.getByRole('button',{name:'+ Add pin',exact:true}).click();
  await page.getByRole('textbox',{name:'Pin name',exact:true}).fill('Fixture pin');
  await page.getByRole('textbox',{name:'https://example.com',exact:true}).fill(`${base}/pinned`);
  await page.getByRole('combobox',{name:'Pin folder',exact:true}).selectOption({label:'Work'});
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Settings saved.'}).waitFor();
  await page.reload();
  assert.equal(await page.getByRole('textbox',{name:'Pin name',exact:true}).inputValue(),'Fixture pin');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export saved configuration'}).click();
  assert.equal((await download).suggestedFilename(),'titan-config.json');
  await page.getByLabel('Import Titan configuration').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
  await page.getByRole('status').filter({hasText:'Invalid Titan configuration'}).waitFor();
  const saved=await worker.evaluate(async()=> (await chrome.storage.local.get('config')).config);
  await page.getByLabel('Import Titan configuration').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await page.getByRole('status').filter({hasText:'Imported into draft'}).waitFor();
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Settings saved.'}).waitFor();
  await worker.evaluate(async(base)=>{await chrome.history.addUrl({url:`${base}/old-history`});for(let i=0;i<12;i++)await chrome.history.addUrl({url:`${base}/history-scroll-${i}`});await chrome.bookmarks.create({title:'Fixture bookmark',url:`${base}/bookmarked`});},base);
  await page.goto('chrome://newtab/');
  assert.ok(!page.url().startsWith(`chrome-extension://${id}/`));
  await page.goto(`chrome-extension://${id}/launcher.html`);
  const search=page.getByRole('combobox',{name:'Search Titan',exact:true});
  await search.fill('/fixture');await page.getByRole('option').filter({hasText:'/fixture · Fixture shortcut'}).waitFor();
  await search.fill('Fixture shortcut');await page.getByRole('option').filter({hasText:'Search or open'}).waitFor();
  assert.equal(await page.getByRole('option').filter({hasText:'/fixture'}).count(),0);
  await search.fill('/g');await search.press('!');assert.equal(await search.inputValue(),'/g!');
  await page.getByRole('option').filter({hasText:'/g! · Google'}).waitFor();
  await search.fill('');
  await page.getByRole('option').filter({hasText:'Fixture pin'}).waitFor();
  assert.doesNotMatch(await page.locator('.results').innerText(),/history|Recent tabs/);
  assert.deepEqual(await page.evaluate(async()=> (await chrome.runtime.sendMessage({type:'search',query:''})).value),[]);
  await search.fill('history-scroll');await page.waitForFunction(()=>document.querySelector('div').shadowRoot.querySelectorAll('.row').length===13);
  const dimensions=await page.locator('.results').evaluate(node=>{const box=node.getBoundingClientRect();return {visible:[...node.querySelectorAll('.row')].filter(row=>{const r=row.getBoundingClientRect();return r.top>=box.top && r.bottom<=box.bottom+1;}).length,scrollable:node.scrollHeight>node.clientHeight};});
  assert.equal(dimensions.visible,5);assert.equal(dimensions.scrollable,true);
  await search.press('ArrowDown');await search.press('ArrowDown');await search.press('ArrowDown');await search.press('ArrowDown');await search.press('ArrowDown');
  assert.ok(await page.locator('.results').evaluate(node=>node.scrollTop>0));
  await search.fill('old-history');await page.getByRole('option').filter({hasText:'history'}).first().waitFor();
  assert.match(await page.locator('.results').innerText(),/old-history/);
  await search.fill('Fixture bookmark');await page.getByRole('option').filter({hasText:'Fixture bookmark'}).first().waitFor();
  await search.fill('/');await page.getByRole('option').filter({hasText:'Pin this page'}).waitFor();
  await page.screenshot({path:path.join(profile,'titan.png')});
  const fixture=await context.newPage();await fixture.goto(base);
  await fixture.waitForTimeout(600);
  await fixture.keyboard.press('j');await fixture.waitForFunction(()=>scrollY>0);
  await fixture.keyboard.press('g');await fixture.keyboard.press('g');await fixture.waitForFunction(()=>scrollY===0);
  const field=fixture.getByRole('textbox',{name:'Typing test'});
  await field.focus();await fixture.keyboard.press('Shift+T');
  assert.equal(await field.inputValue(),'','Normal mode must open Titan from a focused textbox instead of typing T');
  await fixture.keyboard.press('Escape');
  await fixture.waitForTimeout(100);
  await field.focus();await fixture.keyboard.type('xyz');assert.equal(await field.inputValue(),'');
  await fixture.evaluate(()=>{window.keyTrace=[];for(const type of ['keydown','keypress','beforeinput','input'])document.addEventListener(type,e=>window.keyTrace.push({type,key:e.key,data:e.data,prevented:e.defaultPrevented,target:e.target.tagName}),true);});
  await fixture.keyboard.press('i');assert.deepEqual(errors,[]);await fixture.keyboard.type('hello');
  if(await field.inputValue()!=='hello'){
    const debug=await context.newCDPSession(fixture);const doc=await debug.send('DOM.getDocument',{depth:-1,pierce:true});
    const values=[];const walk=n=>{if(n.nodeName==='INPUT'||n.nodeName==='DIALOG'||n.nodeName==='#text')values.push({name:n.nodeName,attrs:n.attributes,text:n.nodeValue});for(const child of [...(n.children||[]),...(n.shadowRoots||[])])walk(child);};walk(doc.root);
    console.log('[DEBUG-focus]',JSON.stringify({active:await fixture.evaluate(()=>({html:document.activeElement.outerHTML,focused:document.hasFocus(),trace:window.keyTrace})),values}));
  }
  assert.equal(await field.inputValue(),'hello');
  await fixture.keyboard.press('Escape');await field.focus();await fixture.keyboard.press('j');assert.equal(await field.inputValue(),'hello');
  await fixture.keyboard.press('g');await fixture.keyboard.press('g');
  // Simulate a site that refocuses its composer and captures document keydown.
  await fixture.evaluate(()=>{window.stolenKeys=0;document.addEventListener('keydown',()=>window.stolenKeys++,true);window.focusTimer=setInterval(()=>document.querySelector('input').focus({preventScroll:true}),20);});
  await fixture.keyboard.press('Shift+T');await fixture.waitForTimeout(100);
  await fixture.keyboard.type('launcher typing');await fixture.waitForTimeout(100);
  assert.equal(await field.inputValue(),'hello');assert.equal(await fixture.evaluate(()=>window.stolenKeys),0);
  const cdp=await context.newCDPSession(fixture);
  const tree=await cdp.send('DOM.getDocument',{depth:-1,pierce:true});
  const findSearch=node=>{if(node.attributes?.includes('Search Titan'))return node;for(const child of [...(node.children||[]),...(node.shadowRoots||[])]){const found=findSearch(child);if(found)return found;}};
  const node=findSearch(tree.root);assert.ok(node,'Titan search exists inside its closed shadow root');
  const {object}=await cdp.send('DOM.resolveNode',{nodeId:node.nodeId});
  const result=await cdp.send('Runtime.callFunctionOn',{objectId:object.objectId,functionDeclaration:'function(){return this.value}',returnByValue:true});
  assert.equal(result.result.value,'launcher typing');
  await fixture.evaluate(()=>clearInterval(window.focusTimer));await fixture.keyboard.press('Escape');
  await fixture.getByRole('heading').click();await fixture.keyboard.press('f');await fixture.keyboard.press('a');await fixture.waitForURL(`${base}/destination`);
  await fixture.waitForTimeout(400);await fixture.keyboard.press('Shift+T');await fixture.keyboard.type('/pin');await fixture.waitForTimeout(300);await fixture.keyboard.press('Enter');
  await page.waitForTimeout(400);
  const afterPin=await worker.evaluate(async()=> (await chrome.storage.local.get('config')).config);
  assert.equal(afterPin.pins.length,2);
  await fixture.keyboard.press('Escape');
  const newPage=context.waitForEvent('page');await fixture.keyboard.press('Shift+1');const pinned=await newPage;await pinned.waitForURL(`${base}/pinned`);
  await page.bringToFront();await search.fill('Titan fixture /pinned');
  await page.getByRole('option').filter({hasText:'Titan fixture /pinned'}).first().waitFor();
  const count=context.pages().length;await search.press('Enter');await page.waitForTimeout(200);assert.equal(context.pages().length,count);
  const active=await worker.evaluate(async()=> (await chrome.tabs.query({active:true,currentWindow:true}))[0].url);assert.equal(active,`${base}/pinned`);
  assert.deepEqual(errors,[]);
  console.log('PASS: real extension settings, persistence, export/import, history/bookmarks, slash commands, page pinning, Vim scroll, typing protection, hints and numbered pins.');
  console.log(`Isolated test profile and screenshot: ${profile}`);
} finally {await context?.close();server.close();}
