// Run with PLAYWRIGHT_PATH=/path/to/playwright/index.mjs node tests/browser.mjs
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import http from 'node:http';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH || 'playwright');
const directory=path.resolve(import.meta.dirname,'..');
const profile=await mkdtemp(path.join(tmpdir(),'titan-browser-test-'));
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Titan fixture '+req.url+'</title><body><h1>Titan test page</h1><a href="/destination">Destination link</a><input aria-label="Typing test"><div style="height:4000px">Long page</div></body>');});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
const base=`http://127.0.0.1:${server.address().port}`;
let context;
try {
  context=await chromium.launchPersistentContext(profile,{executablePath:process.env.CHROMIUM_PATH || '/usr/lib/chromium/chromium',headless:true,args:[`--disable-extensions-except=${directory}`,`--load-extension=${directory}`,'--no-sandbox']});
  const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  let worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  const id=new URL(worker.url()).host;
  const page=await context.newPage();
  // Open shadows only in extension-page tests to inspect controls; shipped UI stays closed.
  await page.addInitScript(()=>{const original=Element.prototype.attachShadow;Element.prototype.attachShadow=function(options){return original.call(this,{...options,mode:'open'});};});
  await page.goto(`chrome-extension://${id}/settings.html`);
  await page.getByRole('button',{name:'+ Add folder',exact:true}).click();
  await page.getByRole('textbox',{name:'Folder name',exact:true}).fill('Work');
  await page.getByRole('button',{name:'+ Add pin',exact:true}).click();
  await page.getByRole('textbox',{name:'Pin name',exact:true}).fill('Fixture pin');
  await page.getByRole('textbox',{name:'https://example.com',exact:true}).fill(`${base}/pinned`);
  await page.getByRole('combobox',{name:'Pin folder',exact:true}).selectOption({label:'Work'});
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Settings saved.'}).waitFor();
  await page.reload();
  assert.equal(await page.getByRole('textbox',{name:'Pin name',exact:true}).inputValue(),'Fixture pin');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export saved configuration'}).click();
  assert.equal((await download).suggestedFilename(),'titan-config.json');
  await page.getByLabel('Import Titan configuration').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
  await page.getByRole('status').filter({hasText:'Invalid Titan configuration'}).waitFor();
  const saved=await worker.evaluate(async()=> (await chrome.storage.local.get('config')).config);
  await page.getByLabel('Import Titan configuration').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await page.getByRole('status').filter({hasText:'Imported into draft'}).waitFor();
  await page.getByRole('button',{name:'Save settings',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Settings saved.'}).waitFor();
  await worker.evaluate(async(base)=>{await chrome.history.addUrl({url:`${base}/old-history`});await chrome.bookmarks.create({title:'Fixture bookmark',url:`${base}/bookmarked`});},base);
  await page.goto(`chrome-extension://${id}/newtab.html`);
  const search=page.getByRole('combobox',{name:'Search Titan',exact:true});
  await page.getByRole('option').filter({hasText:'Fixture pin'}).waitFor();
  await search.fill('old-history');await page.getByRole('option').filter({hasText:'history'}).first().waitFor();
  assert.match(await page.locator('.results').innerText(),/old-history/);
  await search.fill('Fixture bookmark');await page.getByRole('option').filter({hasText:'Fixture bookmark'}).first().waitFor();
  await search.fill('/');await page.getByRole('option').filter({hasText:'Pin this page'}).waitFor();
  await page.screenshot({path:path.join(profile,'titan.png')});
  const fixture=await context.newPage();await fixture.goto(base);
  await fixture.waitForTimeout(600);
  await fixture.keyboard.press('j');await fixture.waitForFunction(()=>scrollY>0);
  await fixture.keyboard.press('g');await fixture.keyboard.press('g');await fixture.waitForFunction(()=>scrollY===0);
  await fixture.getByRole('textbox',{name:'Typing test'}).focus();await fixture.keyboard.press('Shift+T');assert.equal(await fixture.getByRole('textbox').inputValue(),'T');
  await fixture.getByRole('heading').click();await fixture.keyboard.press('f');await fixture.keyboard.press('a');await fixture.waitForURL(`${base}/destination`);
  await fixture.waitForTimeout(400);await fixture.keyboard.press('Shift+T');await fixture.keyboard.type('/pin');await fixture.waitForTimeout(300);await fixture.keyboard.press('Enter');
  await page.waitForTimeout(400);
  const afterPin=await worker.evaluate(async()=> (await chrome.storage.local.get('config')).config);
  assert.equal(afterPin.pins.length,2);
  await fixture.keyboard.press('Escape');
  const newPage=context.waitForEvent('page');await fixture.keyboard.press('Shift+1');const pinned=await newPage;await pinned.waitForURL(`${base}/pinned`);
  await page.bringToFront();await search.fill('Titan fixture /pinned');
  await page.getByRole('option').filter({hasText:'Titan fixture /pinned'}).first().waitFor();
  const count=context.pages().length;await search.press('Enter');await page.waitForTimeout(200);assert.equal(context.pages().length,count);
  const active=await worker.evaluate(async()=> (await chrome.tabs.query({active:true,currentWindow:true}))[0].url);assert.equal(active,`${base}/pinned`);
  assert.deepEqual(errors,[]);
  console.log('PASS: real extension settings, persistence, export/import, history/bookmarks, slash commands, page pinning, Vim scroll, typing protection, hints and numbered pins.');
  console.log(`Isolated test profile and screenshot: ${profile}`);
} finally {await context?.close();server.close();}
